# Generated by Django 4.1.5 on 2023-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSabba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='placa',
            field=models.ImageField(blank=True, null=True, upload_to='placas_rally'),
        ),
    ]
