# Generated by Django 4.1.5 on 2023-02-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSabba', '0002_competencia_placa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='placa',
            new_name='imagen',
        ),
    ]
